### ISSUE TITLE
SQLite 版本出错 SQLSTATE[HY000]: General error: 17 database schema has changed

### ISSUE THREAD

**Issue by aniude** [benzBrake/ShortLinks#4]
调用堆栈：
```
exception 'Typecho_Db_Query_Exception' with message 'SQLSTATE[HY000]: General error: 17 database schema has changed' in /test/build/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /test/build/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo->query('UPDATE typecho_...', Object(PDO), 2, 'UPDATE')
#1 /test/build/var/Widget/Abstract/Options.php(69): Typecho_Db->query(Object(Typecho_Db_Query))
#2 /test/build/var/Helper.php(211): Widget_Abstract_Options->update(Array, Object(Typecho_Db_Query))
#3 /test/build/usr/plugins/ShortLinks/Plugin.php(42): Helper::addAction('shortlinks', 'ShortLinks_Acti...')
#4 [internal function]: ShortLinks_Plugin::activate()
#5 /test/build/var/Widget/Plugins/Edit.php(102): call_user_func(Array)
#6 /test/build/var/Widget/Plugins/Edit.php(308): Widget_Plugins_Edit->activate('ShortLinks')
#7 /test/build/var/Widget/Do.php(82): Widget_Plugins_Edit->action()
#8 /test/build/var/Typecho/Widget.php(221): Widget_Do->execute()
#9 /test/build/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#10 /test/build/index.php(23): Typecho_Router::dispatch()
#11 {main}
```

**Comment by benzBrake** [comment]
理论是能用的，你解决了？
